### ISSUE TITLE
MVPリリース

### ISSUE THREAD

**Issue by yoshihiro1019** [yoshihiro1019/yoshihiroGraduationwork#21]
## 各種情報
サービスの概要とMVPで検証する事柄：ユーザー登録・ログイン・トークンのリフレッシュ・パスワードリセット・ログアウト機能・ユーザー情報取得・トークン検証機能、AIによるトレーニング提案機能（MVPではAI未実装）、BGM機能、周辺のジム検索機能、記録帳機能、部位別トレーニング検索機能
サービス名：FItAIplanner
サービスURL：https://fitplanner-ver2-0.onrender.com/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] ユーザー登録・ログイン・トークンのリフレッシュ・パスワードリセット・ログアウト機能・ユーザー情報取得・トークン検証機能
- [x] AIによるトレーニング提案機能（MVPではAI未実装）
- [x] BGM機能
- [x] 周辺のジム検索機能
- [x] 記録帳機能
- [x] 部位別トレーニング検索機能(本リリースではもっと部位に対する提案するトレーニングの数や画像、動画を追加する予定です、とりあえず最低限の機能だけ実装しました。)
READMEレビュー時に実装予定だった機能が実装できているかがわかるように記載してください。

## サービスイメージがわかるようなスクリーンショット等
管理画面などは特に設定していません

**Comment by kenchasonakai** [comment]
> issueは以下issue用のテンプレートを参考に作成してください。

下記の記載を再度ご確認ください
https://school.runteq.jp/v3/curriculums/graduate_examination/chapters/5#:~:text=%E3%83%AC%E3%83%93%E3%83%A5%E3%83%BC%E3%81%AE%E5%8A%B9%E7%8E%87%E5%8C%96%E3%81%AE%E3%81%9F%E3%82%81issue%E3%81%AF%E4%BB%A5%E4%B8%8Bissue%E7%94%A8%E3%81%AE%E3%83%86%E3%83%B3%E3%83%97%E3%83%AC%E3%83%BC%E3%83%88%E3%82%92%E5%8F%82%E8%80%83%E3%81%AB%E4%BD%9C%E6%88%90%E3%81%97%E3%81%A6%E3%81%8F%E3%81%A0%E3%81%95%E3%81%84%E3%80%82

**Comment by TakenakaEri** [comment]
記録帳機能の保存ができませんでした。エラーの場合は修正して再提出をお願いします。
また、操作の問題なのであれば、開発者の意図した操作手順をコメントに記載をお願いします。

[![Image from Gyazo](https://t.gyazo.com/teams/startup-technology/2b4bd1769097a314eaa90f18d44d0d24.gif)](https://startup-technology.gyazo.com/2b4bd1769097a314eaa90f18d44d0d24)

**Comment by yoshihiro1019** [comment]
![image](https://github.com/user-attachments/assets/e46fa9dd-8dd3-4ab7-aad0-09d3d9a6e3ce)
「トレーニングの種類」の右側に文字が入力できるようになってましてそちらが未入力のまま保存しようとしているので保存が失敗しているのだと思います。
![image](https://github.com/user-attachments/assets/fe59e634-9d3e-4811-b52c-6bc9c923f1b6)

**Comment by kenchasonakai** [comment]
機能確認が取れました。LGTMです。
引き続き本リリースに向けて開発頑張ってください。
どこに何を入力すればいいのかわからず実際に使ってもらうことのハードルが高そうなのでまずは最低限のUIを整えて実際に使ってもらってフィードバックを得られるとよいかと思います。

以下、LGTMを出した方々に共通してお伝えしている内容になります。
（Webアプリを就職活動で活用される方向けの内容になります）

===== 本リリースまでに以下の項目を実装してください =====
□ 独自ドメイン反映
    -> DNSやSSLの対応も必要になるのでアピールになり、URLを書類等に記載するときの見栄えも良くなります。
□ OGP（静的 or 動的）
    -> SNS等でシェアするときの見栄えが良くなります。Webアプリであればどんなアプリでも取り入れられるので対応しておきましょう。
□ RSpec（モデルテスト+システムテスト or モデルテスト+リクエストテスト）
    -> 開発における品質の意識や開発効率の意識の高さをアピールできます。Request Specをメインに最低限各機能に正常にアクセスできるか程度はテストで確認できるようにしておきましょう。
□ CI（GitHubActions）
    -> 実際に開発現場でも使われており、アプリ外で技術のアピールが出来るものです。RSpecと合わせて実装を行いましょう。
□ Rubocopを使ってのリファクタリング
    -> Lintチェックツールは開発現場で広く使われています。コードのLintを整えておくことはチームで開発することを意識するうえでとても大切になるので取り入れておきましょう。

他のプログラミング学習者のWebアプリと異なることをアピールするために、よりインパクトのある機能を複数盛り込むことが重要になってきます。
□ SNSログイン（Google or LINE）
    -> ほとんどのアプリに取り入れられてユーザー体験の向上や技術のアピールにつながるので取り入れましょう。
□ 検索機能のアップデート（オートコンプリート、マルチ検索等）   ※検索機能がある場合
    -> 特にオートコンプリートは検索体験の向上だけではなくJS系の技術も取り入れていることをアピール出来るので積極的に取り入れましょう。

ユーザー体験という面では以下の項目も大切です。
□ オートログイン
    -> ユーザー登録後に再度ログイン操作を行わせないことでユーザー体験を向上させられます。
□ 使い方説明がある
    -> 初めて訪れたユーザーに呈して使い方の説明があることで体験を向上させられます。
□ レスポンシブ対応
    -> いずれのデバイスでも綺麗にサービスが活用できることで体験が良くなります。
□ 利用規約・プライバシーポリシーを未ログイン状態でも確認できる
    -> 利用規約・プライバシーポリシーがあることで、ちゃんとしたサービスという印象を与えられます。
□ ローディングアニメーション（処理が重い箇所）
    -> 処理が重い箇所に何の対応も無いとユーザーが正しく操作できたのか困惑してしまいます。そうした際はローディングアニメーションを表示させることで体験が向上します。
