### ISSUE TITLE
Projectにissue書き出し

### ISSUE THREAD

**Issue by yoshihiro1019** [yoshihiro1019/yoshihiroGraduationwork#6]
最初ISUUE一覧ページお送りしたんですが、送れなかったので色々試していたらこのページがなぜかお送りできました(´；д；`)

## 質問
クリアしたRAILS基礎のデータをほかのリポジトリに移してアプリ制作を始めてもよろしいでしょうか？

**Comment by Tsuchiya2** [comment]
![image](https://github.com/user-attachments/assets/4bf9064f-5800-4114-afeb-1eb538c65c4b)

↑の提出フォーマットに沿って概要を記載してください。

> クリアしたRAILS基礎のデータをほかのリポジトリに移してアプリ制作を始めてもよろしいでしょうか？

データというのが何を指しているのか分かりませんが...ゼロから作成してください。

**Comment by yoshihiro1019** [comment]
前回はプルリクエストがなぜか送信できなかったのですが今回は送れましたので先ほど送信させて頂きました
